# Generated by Django 4.1.7 on 2023-04-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saize', '0003_alter_document_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='output',
            field=models.ImageField(default='output/output.jpg', upload_to=''),
        ),
    ]
