# Generated by Django 4.1.7 on 2023-04-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saize', '0005_alter_document_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='output',
            field=models.ImageField(upload_to='output/'),
        ),
    ]
